Rails:
    Enabled: true

Metrics/BlockLength:
    Max: 25
    Exclude:
      - 'config/routes.rb'
      - 'spec/**/*.rb'
      - 'config/deploy.rb'

Metrics/LineLength:
    Max: 120

Metrics/MethodLength:
    Max: 15

Metrics/ClassLength:
    Max: 200

Rails/Exit:
    Exclude:
      - 'config/deploy.rb'

Lint/AssignmentInCondition:
    Exclude:
      - 'bin/spring'

AllCops:
    Exclude:
      - 'db/migrate/**'
      - 'db/schema.rb'
      - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
